site_name: BTAA-GIN Metadata Documentation
#site_url: https://geoblacklight.org/docs
#repo_url: https://github.com/geoblacklight/docs/main
#edit_uri: https://github.com/geoblacklight/docs/main
theme: 
    name: readthedocs
#    logo: img/geoblacklight-logo-small@2x.png
    highlightjs: true
    titles_only: true
    include_homepage_in_sidebar: true
    
nav:
- Home: 'index.md'
- Overview:
     - 'Metadata for the BTAA Geoportal': 'about.md'
     - 'Custom Elements' : 'b1g-custom-elements.md'
     - 'Collection Model' : 'relations.md'
     - 'Entry Guidelines' : 'entry-usage-guidelines.md'
     
- Workflows:
      - 'Lifecycle' : 'workflow.md'
      - 'GEOMG' : 'GEOMG.md'