site_name: GeoBTAA Metadata Handbook
site_author: Big Ten Academic Alliance Geospatial Information Network
copyright : "2022"
repo_url: https://github.com/geobtaa/metadata
theme: 
   name: material
   features:
#     - navigation.instant
      - navigation.sections
      - content.tooltips
#      - navigation.tabs
#      - navigation.tabs.sticky
      - navigation.top
   logo: images/btaa-logo-white.png
   icon:
      repo: fontawesome/brands/github
#    highlightjs: true
#   titles_only: true
#   include_homepage_in_sidebar: false
plugins:
      - search
      - with-pdf:
            output_path: Desktop/b1g-handbook.pdf
      
#   - pdf-export:
#       combined: true
#   - git-revision-date-localized:
#       enable_creation_date: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

    
nav:
- HOME: 'index.md'

- GeoBTAA Metadata Profile: 
     - 'Overview' : 'components.md'
     - 'Local Input Guidelines': 'inputGuidelines.md'
     - 'Custom Elements' : 'b1g-custom-elements.md'
     - 'Supplemental Metadata' : 'supplementalMetadata.md'
     - 'Editing Template' : 'editingTemplate.md'

- Content Organization Model: 
     - 'Diagram' : 'model.md'
     - 'Resource Classes' : 'resourceClasses.md'

- Curation Workflows:
      - 'Identifying Resources' : 'identify.md'
      - 'Resource Lifecycle' : 'lifecycle.md'
      - 'Harvest Guide' :  'harvestGuide.md'
      - 'GEOMG Metadata Toolkit' : 'geomg.md'