# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Weekly Team Sync
on:
  schedule:
    - cron: 30 13 * * 2

jobs:
  create_issue:
    name: Scan ArcGIS Hubs
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          assignees: "karenmajewicz"
          labels: "New records"
          title: "Harvest ArcGIS Hubs"
          body: |
            ### To do

            - [ ] Download list of ArcGIS Hubs
            - [ ] Run scan
            - [ ] Upload new items to GEOMG
            - [ ] Unpublish retired items
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
